/* Generated by tests/lex/gen_tab.py from MSTTSFrontendENU.dll (Anna, TTS20). Do not edit. */

/* ambiguous words @0x0D604B90 (72 x 0x30): word, prons, POS, handler (0x0D60C4D8) */
static const lex_entry AMBIG[72] = {
    {"a", {"ey 1", "ax 1", NULL}, {0x1000, 0x4006, 0x0}, 8}, /* 0 */
    {"al", {"ey 2 - eh 1 l", "ao 1 l", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 1 */
    {"apr", {"ey 1 & p iy 1 & aa 1 r", "ey 1 - p r ih l", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 2 */
    {"as", {"ey - eh 1 s", "ae 1 z", NULL}, {0x1000, 0x4003, 0x0}, 3}, /* 3 */
    {"bu", {"b uh 1 - sh ax l", "b uh 1 - sh ax l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 4 */
    {"c", {"s eh 1 l - s iy - ax s", "s iy 1", NULL}, {0x1000, 0x1000, 0x0}, 6}, /* 5 */
    {"cal", {"k ae 1 - l ax - r iy", "k ae 1 - l ax - r iy z", "k ae 1 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 6 */
    {"cl", {"s eh 1 n - t ax - l iy 2 - t ax r", "s eh 1 n - t ax - l iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 7 */
    {"cm", {"s eh 1 n - t ax - m iy - t ax r", "s eh 1 n - t ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 8 */
    {"ct", {"s iy 2 - t iy 1", "k ao 1 r t", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 9 */
    {"cu", {"s iy 1 - y uw 1", "k y uw 1 - b ih k", NULL}, {0x1000, 0x1000, 0x0}, 7}, /* 10 */
    {"db", {"d eh 1 - s ax - b eh l", "d eh 1 - s ax - b eh 2 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 11 */
    {"deg", {"d ih - g r iy 1", "d ih - g r iy 1 z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 12 */
    {"dr", {"d aa 1 k - t er r", "d r ay 1 v", NULL}, {0x1000, 0x1000, 0x0}, 1}, /* 13 */
    {"f", {"f eh 1 - r ax n - h ay 2 t", "eh 1 f", NULL}, {0x1000, 0x1000, 0x0}, 6}, /* 14 */
    {"fig", {"f ih 1 - g y ax r", "f ih 1 g", NULL}, {0x1000, 0x1000, 0x0}, 2}, /* 15 */
    {"figs", {"f ih 1 - g y ax r z", "f ih 1 g z", NULL}, {0x1000, 0x1000, 0x0}, 2}, /* 16 */
    {"fl", {"eh 2 f - eh 1 l", "f l uw 1 - ih d", NULL}, {0x1000, 0x1000, 0x0}, 7}, /* 17 */
    {"ft", {"f uh 1 t", "f iy 1 t", "f ao 1 r t"}, {0x1000, 0x1000, 0x1000}, 0}, /* 18 */
    {"g", {"g r ae 1 m", "g r ae 1 m z", "jh iy 1"}, {0x1000, 0x1000, 0x1000}, 5}, /* 19 */
    {"gov", {"g ah 1 - v ax - n ax r", "g ah 1 v", NULL}, {0x1000, 0x1000, 0x0}, 1}, /* 20 */
    {"hi", {"ey 2 ch - ay 1", "h ay 1", NULL}, {0x1000, 0x5000, 0x0}, 3}, /* 21 */
    {"hr", {"aw 1 - ax r", "aw 1 - ax r z", "ey 1 ch - aa 1 r"}, {0x1000, 0x1000, 0x1000}, 5}, /* 22 */
    {"it", {"ay 1 - t iy 1", "ih 1 t", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 23 */
    {"j", {"jh aw 1 l", "jh aw 1 l z", "jh ey 1"}, {0x1000, 0x1000, 0x1000}, 5}, /* 24 */
    {"k", {"k eh 1 l - v ih n", "k ey 1", NULL}, {0x1000, 0x1000, 0x0}, 6}, /* 25 */
    {"kb", {"k ih 1 - l ax - b ay 2 t", "k ih 1 - l ax - b ay 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 26 */
    {"kcal", {"k ih 1 - l ax - k ae 2 - l ax - r iy", "k ih 1 - l ax - k ae 2 - l ax - r iy z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 27 */
    {"kg", {"k ih 1 - l ax - g r ae m", "k ih 1 - l ax - g r ae 2 m z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 28 */
    {"kj", {"k ih 1 - l ax - jh uw 2 l", "k ih 1 - l ax - jh uw 2 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 29 */
    {"km", {"k ih 1 - l ax - m iy - t ax r", "k ih 1 - l ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 30 */
    {"kw", {"k ih 1 - l ax - w aa 2 t ", "k ih 1 - l ax - w aa 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 31 */
    {"l", {"l ih 1 - t ax r", "l iy 1 - t ax r z", "eh 1 l"}, {0x1000, 0x1000, 0x1000}, 5}, /* 32 */
    {"la", {"eh l & ey 1", "l aa 1", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 33 */
    {"lb", {"p aw 1 n d", "p aw 1 n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 34 */
    {"lts", {"eh 2 l - t iy 2 - eh 1 s", "l uw - t eh 1 - n ax n t s", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 35 */
    {"m", {"m iy 1 - t ax r", "m iy 1 - t ax r z", "eh 1 m"}, {0x1000, 0x1000, 0x1000}, 5}, /* 36 */
    {"ma", {"eh 2 m - ey 1", "m aa 1", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 37 */
    {"mar", {"m aa 1 r ch", "m aa 1 r", NULL}, {0x1000, 0x2000, 0x0}, 4}, /* 38 */
    {"mb", {"m eh 1 - g ax - b ay 2 t", "m eh 1 - g ax - b ay 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 39 */
    {"me", {"eh 2 m - iy 1", "m iy 1", NULL}, {0x1000, 0x1003, 0x0}, 3}, /* 40 */
    {"mg", {"m ih 1 - l ax - g r ae 2 m", "m ih 1 - l ax - g r ae 2 m z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 41 */
    {"mi", {"m ay 1 l", "m ay 1 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 42 */
    {"min", {"m ih 1 - n ih t", "m ih 1 - n ih t s", "m ih 1 - n ax - m ax m"}, {0x1000, 0x1000, 0x1000}, 0}, /* 43 */
    {"ml", {"m ih 1 - l ax - l iy - t ax r", "m ih 1 - l ax - l iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 44 */
    {"mm", {"m ih 1 - l ax - m iy 2 - t ax r", "m ih 1 - l ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 45 */
    {"mpg", {"m ay 1 l - p er r - g ae 1 - l ax n", "m ay 1 l z - p er r - g ae 1 - l ax n", "eh 1 m - p iy 1 - jh iy 1"}, {0x1000, 0x1000, 0x1000}, 0}, /* 46 */
    {"mph", {"m ay 1 l - p er - r aw 1 - ax r", "m ay 1 l z - p er - r aw 1 - ax r", "eh 1 m - p iy 1 - ey 1 ch"}, {0x1000, 0x1000, 0x1000}, 0}, /* 47 */
    {"ms", {"m ih 1 - l ih - s eh - k ax n d", "m ih 1 - l ax - s eh 2 - k ax n d z", "eh 2 m - eh 1 s"}, {0x1000, 0x1000, 0x1000}, 5}, /* 48 */
    {"msec", {"m ih 1 - l ih - s eh - k ax n d", "m ih 1 - l ax - s eh 2 - k ax n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 49 */
    {"mt", {"eh 2 m - t iy 1", "m aw 1 n t", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 50 */
    {"oh", {"ow 2 & ey 1 ch", "ow 1", NULL}, {0x1000, 0x5000, 0x0}, 3}, /* 51 */
    {"or", {"ow - aa 1 r", "ao 1 r", NULL}, {0x1000, 0x4004, 0x0}, 3}, /* 52 */
    {"oz", {"aw 1 n s", "aw 1 n - s ih z", "aa 1 z"}, {0x1000, 0x1000, 0x1000}, 0}, /* 53 */
    {"p", {"p ey 1 jh", "p iy 1", NULL}, {0x1000, 0x1000, 0x0}, 2}, /* 54 */
    {"pa", {"p iy 1 - ey 2", "p aa 1", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 55 */
    {"pg", {"p iy 1 - jh iy 1", "p ey 1 jh", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 56 */
    {"po", {"p iy 1 & ow 2", "p ow 1", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 57 */
    {"polish", {"p ow 1 - l ih sh", "p aa 1 - l ih sh", "p aa 1 - l ih sh"}, {0x3001, 0x2000, 0x1000}, 9}, /* 58 */
    {"qt", {"k w ao 1 r t", "k w ao 1 r t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 59 */
    {"sat", {"s ae 1 - t ax r - d ey", "s ae 1 t", NULL}, {0x1000, 0x2000, 0x0}, 4}, /* 60 */
    {"sec", {"s eh 1 - k ax n d", "s eh 1 - k ax n d z", "eh 1 s - iy 1 - s iy 1"}, {0x1000, 0x1000, 0x1000}, 5}, /* 61 */
    {"sq", {"s k w eh 1 r", "s k w eh 1 r", NULL}, {0x1000, 0x1000, 0x0}, 7}, /* 62 */
    {"sr", {"s iy 1 - n y ax r", "eh s & aa 1 r", NULL}, {0x1000, 0x1000, 0x0}, 10}, /* 63 */
    {"st", {"s ey 1 n t", "s t r iy 1 t", NULL}, {0x1000, 0x1000, 0x0}, 1}, /* 64 */
    {"tbsp", {"t ey 1 - b ax l - s p uw 2 n", "t ey 1 - b ax l - s p uw 2 n z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 65 */
    {"tsp", {"t iy 1 - s p uw 2 n", "t iy 1 - s p uw 2 n z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 66 */
    {"us", {"y uw 2 - eh 1 s", "ah 1 s", NULL}, {0x1000, 0x1003, 0x0}, 3}, /* 67 */
    {"wed", {"w eh 1 n z - d ey", "w eh 1 d", NULL}, {0x1000, 0x2000, 0x0}, 4}, /* 68 */
    {"wy", {"d ah 2 - b ax l - y uw - w ay 1", "w ey 1", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 69 */
    {"yd", {"y aa 1 r d", "y aa 1 r d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 70 */
    {"yr", {"y iy 1 r", "y ih 1 r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 71 */
};

/* abbreviations @0x0D602A30 (178 x 0x30): word, prons, POS, tag handler (0x0D60C4AC, -1 = fixed) */
static const lex_entry ABBR[178] = {
    {"a", {"ey 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 0, sentence handler 0 */
    {"amp", {"ae 1 m p", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 1, sentence handler 0 */
    {"app", {"ey 1 - p iy 2 - p iy 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 2, sentence handler 0 */
    {"apr", {"ey 1 - p r ih l", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 3, sentence handler 0 */
    {"apt", {"ax - p aa 1 r t - m ax n t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 4, sentence handler 0 */
    {"assoc", {"ax - s ow 2 - s iy - ey 1 - sh ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 5, sentence handler 0 */
    {"asst", {"ax - s ih 1 - s t ax n t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 6, sentence handler 0 */
    {"aug", {"ao 1 - g ah s t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 7, sentence handler 0 */
    {"ave", {"ae 1 - v ax - n uw 2", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 8, sentence handler 0 */
    {"b", {"b iy 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 9, sentence handler -1 */
    {"bldg", {"b ih 2 l - d ih ng", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 10, sentence handler 0 */
    {"blvd", {"b uw 1 - l ax - v aa 2 r d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 11, sentence handler 0 */
    {"bu", {"b uh 1 - sh ax l", "b uh 1 - sh ax l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 12, sentence handler 0 */
    {"c", {"s eh 1 l - s iy - ax s", "s iy 1", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 13, sentence handler 0 */
    {"cal", {"k ae 1 - l ax - r iy", "k ae 1 - l ax - r iy z", "k ae 1 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 14, sentence handler 0 */
    {"cals", {"k ae 1 - l ax - r iy z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 15, sentence handler 0 */
    {"capt", {"k ae 1 p - t ih n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 16, sentence handler 0 */
    {"ch", {"ch ae 1 p - t ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 17, sentence handler 0 */
    {"cl", {"s eh 1 n - t ax - l iy 2 - t ax r", "s eh 1 n - t ax - l iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 18, sentence handler 0 */
    {"cm", {"s eh 1 n - t ax - m iy - t ax r", "s eh 1 n - t ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 19, sentence handler 0 */
    {"cms", {"s eh 1 n - t ax - m iy 2 - t ax r z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 20, sentence handler 0 */
    {"cntr", {"s eh 1 n - t ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 21, sentence handler 0 */
    {"co", {"k ah 1 m - p ax - n iy", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 22, sentence handler 1 */
    {"cont", {"k ax n - t ih 1 - n y uw d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 23, sentence handler 0 */
    {"corp", {"k ao 2 r - p ax - r ey 1 - sh ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 24, sentence handler 0 */
    {"ct", {"k ao 1 r t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 25, sentence handler 1 */
    {"ctr", {"s eh 1 n - t ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 26, sentence handler 0 */
    {"cu", {"k y uw 1 - b ih k", "k y uw 1 - b ih k", NULL}, {0x1000, 0x1000, 0x0}, 4}, /* 27, sentence handler 1 */
    {"d", {"d iy 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 28, sentence handler -1 */
    {"db", {"d eh 1 - s ax - b eh l", "d eh 1 - s ax - b eh 2 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 29, sentence handler 0 */
    {"dec", {"d ih - s eh 1 m - b ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 30, sentence handler 0 */
    {"deg", {"d ih - g r iy 1", "d ih - g r iy 1 z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 31, sentence handler 0 */
    {"dept", {"d ih - p aa 1 r t - m ax n t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 32, sentence handler 0 */
    {"dist", {"d ih 1 - s t r ih k t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 33, sentence handler 0 */
    {"doc", {"d aa 1 k", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 34, sentence handler 0 */
    {"doz", {"d ah 1 - z ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 35, sentence handler 0 */
    {"dr", {"d aa 1 k - t er r", "d r ay 1 v", NULL}, {0x1000, 0x1000, 0x0}, 1}, /* 36, sentence handler 0 */
    {"e", {"iy 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 37, sentence handler -1 */
    {"ed", {"eh 2 - jh ax - k ey 1 - sh ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 38, sentence handler 1 */
    {"esq", {"ax - s k w ay 1 - ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 39, sentence handler 0 */
    {"est", {"ax - s t ae 1 - b l ih sh t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 40, sentence handler 0 */
    {"etc", {"eh t - s eh 1 - t ax - r ax", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 41, sentence handler 0 */
    {"ex", {"ih g - z ae 1 m - p ax l", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 42, sentence handler 1 */
    {"ext", {"ih k - s t eh 1 n - sh ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 43, sentence handler 0 */
    {"f", {"f eh 1 - r ax n - h ay 2 t", "eh 1 f", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 44, sentence handler 0 */
    {"feb", {"f eh 1 - b r uh - eh 2 - r iy", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 45, sentence handler 0 */
    {"fig", {"f ih 1 - g y ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 46, sentence handler 1 */
    {"figs", {"f ih 1 - g y ax r z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 47, sentence handler 1 */
    {"fl", {"f l uw 1 - ih d", "f l uw 1 - ih d", NULL}, {0x1000, 0x1000, 0x0}, 4}, /* 48, sentence handler 1 */
    {"fn", {"f uh 1 t - n ow 2 t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 49, sentence handler 0 */
    {"freq", {"f r iy 1 - k w ax n - s iy", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 50, sentence handler 0 */
    {"fri", {"f r ay 1 - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 51, sentence handler 0 */
    {"ft", {"f uh 1 t", "f iy 1 t", "f ao 1 r t"}, {0x1000, 0x1000, 0x1000}, 0}, /* 52, sentence handler 0 */
    {"fwd", {"f ao 1 r - w ax r d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 53, sentence handler 0 */
    {"g", {"g r ae 1 m", "g r ae 1 m z", "jh iy 1"}, {0x1000, 0x1000, 0x1000}, 0}, /* 54, sentence handler 1 */
    {"gal", {"g ae 1 - l ax n", "g ae 1 - l ax n z", "g ae 1 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 55, sentence handler 0 */
    {"gen", {"jh eh 1 - n ax - r ax l", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 56, sentence handler -1 */
    {"gov", {"g ah 1 - v ax - n ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 57, sentence handler 1 */
    {"h", {"ey 1 ch", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 58, sentence handler -1 */
    {"hr", {"aw 1 - ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 59, sentence handler 1 */
    {"hrs", {"aw 1 - ax r z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 60, sentence handler 0 */
    {"ht", {"h ay 1 t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 61, sentence handler 0 */
    {"hwy", {"h ay 1 - w ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 62, sentence handler 0 */
    {"hz", {"h er 1 r t s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 63, sentence handler 0 */
    {"i", {"ay 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 64, sentence handler -1 */
    {"in", {"ih 1 n ch", "ih 1 n - ch ih z", "ih 1 n"}, {0x1000, 0x1000, 0x4009}, 0}, /* 65, sentence handler 1 */
    {"inc", {"ih n - k ao 1 r - p ax - r ey 2 - t ih d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 66, sentence handler 0 */
    {"incl", {"ih n - k l uw 1 - d ih d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 67, sentence handler 0 */
    {"intl", {"ih n - t er r - n ae 1 - sh ax - n ax l", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 68, sentence handler 0 */
    {"is", {"ay 1 - l ax n d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 69, sentence handler 2 */
    {"j", {"jh aw 1 l", "jh aw 1 l z", "jh ey 1"}, {0x1000, 0x1000, 0x1000}, 0}, /* 70, sentence handler 1 */
    {"jan", {"jh ae 1 - n y uw - eh 2 - r iy", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 71, sentence handler 1 */
    {"jr", {"jh uw 1 - n y ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 72, sentence handler 0 */
    {"jul", {"jh uw - l ay 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 73, sentence handler 0 */
    {"jun", {"jh uw 1 n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 74, sentence handler 0 */
    {"k", {"k eh 1 l - v ih n", "k ey 1", NULL}, {0x1000, 0x1000, 0x0}, 3}, /* 75, sentence handler 0 */
    {"kb", {"k ih 1 - l ax - b ay 2 t", "k ih 1 - l ax - b ay 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 76, sentence handler 0 */
    {"kcal", {"k ih 1 - l ax - k ae 2 - l ax - r iy", "k ih 1 - l ax - k ae 2 - l ax - r iy z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 77, sentence handler 0 */
    {"kg", {"k ih 1 - l ax - g r ae m", "k ih 1 - l ax - g r ae 2 m z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 78, sentence handler 0 */
    {"kgs", {"k ih 1 - l ax - g r ae 2 m z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 79, sentence handler 0 */
    {"khz", {"k ih 1 - l ax - h er r t s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 80, sentence handler 0 */
    {"kj", {"k ih 1 - l ax - jh uw 2 l", "k ih 1 - l ax - jh uw 2 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 81, sentence handler 0 */
    {"km", {"k ih 1 - l ax - m iy - t ax r", "k ih 1 - l ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 82, sentence handler 0 */
    {"kw", {"k ih 1 - l ax - w aa 2 t ", "k ih 1 - l ax - w aa 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 83, sentence handler 0 */
    {"l", {"l ih 1 - t ax r", "l iy 1 - t ax r z", "eh 1 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 84, sentence handler 1 */
    {"lb", {"p aw 1 n d", "p aw 1 n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 85, sentence handler 0 */
    {"lbs", {"p aw 1 n d z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 86, sentence handler 0 */
    {"lg", {"l aa 1 r jh", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 87, sentence handler 0 */
    {"ln", {"l ey 1 n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 88, sentence handler 0 */
    {"lt", {"l uw - t eh 1 - n ax n t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 89, sentence handler -1 */
    {"ltd", {"l ih 1 - m ih - t ih d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 90, sentence handler 0 */
    {"m", {"m iy 1 - t ax r", "m iy 1 - t ax r z", "eh 1 m"}, {0x1000, 0x1000, 0x1000}, 0}, /* 91, sentence handler 1 */
    {"mar", {"m aa 1 r ch", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 92, sentence handler 0 */
    {"mb", {"m eh 1 - g ax - b ay 2 t", "m eh 1 - g ax - b ay 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 93, sentence handler 0 */
    {"mfg", {"m ae 2 - n y ax - f ae 1 k - ch ax - r ih ng", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 94, sentence handler 0 */
    {"mg", {"m ih 1 - l ax - g r ae 2 m", "m ih 1 - l ax - g r ae 2 m z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 95, sentence handler 0 */
    {"mgr", {"m ae 1 - n ih - jh ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 96, sentence handler 0 */
    {"mgs", {"m ih 1 - l ax - g r ae 2 m z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 97, sentence handler 0 */
    {"mhz", {"m eh 1 - g ax - h er r t s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 98, sentence handler 0 */
    {"mi", {"m ay 1 l", "m ay 1 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 99, sentence handler 0 */
    {"mic", {"m ay 1 k", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 100, sentence handler 0 */
    {"min", {"m ih 1 - n ih t", "m ih 1 - n ih t s", "m ih 1 - n ax - m ax m"}, {0x1000, 0x1000, 0x1000}, 0}, /* 101, sentence handler 0 */
    {"misc", {"m ih 2 - s ax l - ey 1 - n iy - ax s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 102, sentence handler 0 */
    {"ml", {"m ih 1 - l ax - l iy - t ax r", "m ih 1 - l ax - l iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 103, sentence handler 0 */
    {"mm", {"m ih 1 - l ax - m iy 2 - t ax r", "m ih 1 - l ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 104, sentence handler 0 */
    {"mon", {"m ah 1 n - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 105, sentence handler 0 */
    {"mr", {"m ih 1 - s t ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 106, sentence handler -1 */
    {"mrs", {"m ih 1 - s ih z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 107, sentence handler -1 */
    {"ms", {"m ih 1 z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 108, sentence handler 1 */
    {"msec", {"m ih 1 - l ih - s eh - k ax n d", "m ih 1 - l ax - s eh 2 - k ax n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 109, sentence handler 0 */
    {"msecs", {"m ih 1 - l ax - s eh 2 - k ax n d z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 110, sentence handler 0 */
    {"mt", {"m aw 1 n t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 111, sentence handler 0 */
    {"mtn", {"m aw 1 n - t ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 112, sentence handler 0 */
    {"n", {"eh 1 n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 113, sentence handler -1 */
    {"no", {"n ah 1 m - b er r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 114, sentence handler 1 */
    {"nov", {"n ow - v eh 1 m - b ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 115, sentence handler 0 */
    {"o", {"ow 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 116, sentence handler -1 */
    {"oct", {"aa k - t ow 1 - b ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 117, sentence handler 0 */
    {"op", {"ow 1 - p ax s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 118, sentence handler 1 */
    {"oz", {"aw 1 n s", "aw 1 n - s ih z", "aa 1 z"}, {0x1000, 0x1000, 0x1000}, 0}, /* 119, sentence handler 0 */
    {"ozs", {"aw 1 n - s ih z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 120, sentence handler 0 */
    {"p", {"p ey 1 jh", "p iy 1", NULL}, {0x1000, 0x1000, 0x0}, 2}, /* 121, sentence handler 0 */
    {"pg", {"p ey 1 jh", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 122, sentence handler 1 */
    {"pgs", {"p ey 1 - jh ih z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 123, sentence handler 0 */
    {"pkg", {"p ae 1 - k ih jh", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 124, sentence handler 0 */
    {"pkwy", {"p aa 1 r - k w ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 125, sentence handler 0 */
    {"pl", {"p l ey 1 s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 126, sentence handler 0 */
    {"pp", {"p ey 1 - jh ih z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 127, sentence handler 0 */
    {"pres", {"p r eh 1 - z ax - d ax n t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 128, sentence handler -1 */
    {"prof", {"p r ax - f eh 1 - s ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 129, sentence handler -1 */
    {"pt", {"p oy 1 n t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 130, sentence handler 0 */
    {"q", {"k y uw 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 131, sentence handler -1 */
    {"qt", {"k w ao 1 r t", "k w ao 1 r t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 132, sentence handler 0 */
    {"r", {"aa 1 r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 133, sentence handler -1 */
    {"rd", {"r ow 1 d", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 134, sentence handler 0 */
    {"rec", {"r eh 1 k", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 135, sentence handler 0 */
    {"rep", {"r eh 2 - p r ih - z eh 1 n - t ax - t ih v", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 136, sentence handler 0 */
    {"rt", {"r uw 1 t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 137, sentence handler 0 */
    {"rte", {"r uw 1 t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 138, sentence handler 0 */
    {"s", {"eh 1 s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 139, sentence handler -1 */
    {"sat", {"s ae 1 - t ax r - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 140, sentence handler 2 */
    {"sec", {"s eh 1 - k ax n d", "s eh 1 - k ax n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 141, sentence handler 1 */
    {"sen", {"s eh 1 - n ax - t ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 142, sentence handler -1 */
    {"sep", {"s eh p - t eh 1 m - b ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 143, sentence handler 0 */
    {"sept", {"s eh p - t eh 1 m - b ax r", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 144, sentence handler 0 */
    {"sm", {"s m ao 1 l", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 145, sentence handler 0 */
    {"sq", {"s k w eh 1 r", "s k w eh 1 r", NULL}, {0x1000, 0x1000, 0x0}, 4}, /* 146, sentence handler 0 */
    {"sr", {"s iy 1 - n y ax r", "eh s & aa 1 r", NULL}, {0x1000, 0x1000, 0x0}, -1}, /* 147, sentence handler 3 */
    {"st", {"s ey 1 n t", "s t r iy 1 t", NULL}, {0x1000, 0x1000, 0x0}, 1}, /* 148, sentence handler 0 */
    {"ste", {"s w iy 1 t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 149, sentence handler 0 */
    {"sun", {"s ah 1 n - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 150, sentence handler 1 */
    {"t", {"t iy 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 151, sentence handler -1 */
    {"tbsp", {"t ey 1 - b ax l - s p uw 2 n", "t ey 1 - b ax l - s p uw 2 n z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 152, sentence handler 0 */
    {"tech", {"t eh 1 k", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 153, sentence handler 0 */
    {"thu", {"th er 1 r z - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 154, sentence handler 0 */
    {"thur", {"th er 1 r z - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 155, sentence handler 0 */
    {"thurs", {"th er 1 r z - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 156, sentence handler 0 */
    {"tsp", {"t iy 1 - s p uw 2 n", "t iy 1 - s p uw 2 n z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 157, sentence handler 0 */
    {"tue", {"t uw 1 z - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 158, sentence handler 0 */
    {"tues", {"t uw 1 z - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 159, sentence handler 0 */
    {"u", {"y uw 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 160, sentence handler -1 */
    {"univ", {"y uw 2 - n ih - v er 1 r - s ax - t iy", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 161, sentence handler 0 */
    {"v", {"v iy 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 162, sentence handler -1 */
    {"ver", {"v er 1 r - zh ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 163, sentence handler 0 */
    {"vers", {"v er 1 r - zh ax n", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 164, sentence handler 0 */
    {"vol", {"v aa 1 - l y ax m", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 165, sentence handler 0 */
    {"vs", {"v er 1 r - s ax s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 166, sentence handler 0 */
    {"w", {"d ah 1 - b ax - l y uw", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 167, sentence handler -1 */
    {"wed", {"w eh 1 n z - d ey", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 168, sentence handler 2 */
    {"wk", {"w iy 1 k ", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 169, sentence handler 0 */
    {"wt", {"w ey 1 t", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 170, sentence handler 0 */
    {"wy", {"w ey 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 171, sentence handler 0 */
    {"x", {"eh 1 k s", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 172, sentence handler -1 */
    {"y", {"w ay 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 173, sentence handler -1 */
    {"yd", {"y aa 1 r d", "y aa 1 r d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 174, sentence handler 0 */
    {"yds", {"y aa 1 r d z", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 175, sentence handler 0 */
    {"yr", {"y iy 1 r", "y ih 1 r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 176, sentence handler 0 */
    {"z", {"z iy 1", NULL, NULL}, {0x1000, 0x0, 0x0}, -1}, /* 177, sentence handler -1 */
};

/* post-lexical words @0x0D605910 (43 x 0x30): word, prons, POS, handler (0x0D60C530) */
static const lex_entry POST[43] = {
    {"bu", {"b uh 1 - sh ax l", "b uh 1 - sh ax l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 0 */
    {"cal", {"k ae 1 - l ax - r iy", "k ae 1 - l ax - r iy z", "k ae 1 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 1 */
    {"cl", {"s eh 1 n - t ax - l iy 2 - t ax r", "s eh 1 n - t ax - l iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 2 */
    {"cm", {"s eh 1 n - t ax - m iy - t ax r", "s eh 1 n - t ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 3 */
    {"db", {"d eh 1 - s ax - b eh l", "d eh 1 - s ax - b eh 2 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 4 */
    {"deg", {"d ih - g r iy 1", "d ih - g r iy 1 z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 5 */
    {"ft", {"f uh 1 t", "f iy 1 t", "f ao 1 r t"}, {0x1000, 0x1000, 0x1000}, 0}, /* 6 */
    {"g", {"g r ae 1 m", "g r ae 1 m z", "jh iy 1"}, {0x1000, 0x1000, 0x1000}, 0}, /* 7 */
    {"gal", {"g ae 1 - l ax n", "g ae 1 - l ax n z", "g ae 1 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 8 */
    {"hr", {"aw 1 - ax r", "aw 1 - ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 9 */
    {"in", {"ih 1 n ch", "ih 1 n - ch ih z", "ih 1 n"}, {0x1000, 0x1000, 0x4009}, 0}, /* 10 */
    {"j", {"jh aw 1 l", "jh aw 1 l z", "jh ey 1"}, {0x1000, 0x1000, 0x1000}, 0}, /* 11 */
    {"kb", {"k ih 1 - l ax - b ay 2 t", "k ih 1 - l ax - b ay 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 12 */
    {"kcal", {"k ih 1 - l ax - k ae 2 - l ax - r iy", "k ih 1 - l ax - k ae 2 - l ax - r iy z", "k ey 1 - k ae 2 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 13 */
    {"kg", {"k ih 1 - l ax - g r ae m", "k ih 1 - l ax - g r ae 2 m z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 14 */
    {"kj", {"k ih 1 - l ax - jh uw 2 l", "k ih 1 - l ax - jh uw 2 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 15 */
    {"km", {"k ih 1 - l ax - m iy - t ax r", "k ih 1 - l ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 16 */
    {"kw", {"k ih 1 - l ax - w aa 2 t ", "k ih 1 - l ax - w aa 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 17 */
    {"l", {"l ih 1 - t ax r", "l iy 1 - t ax r z", "eh 1 l"}, {0x1000, 0x1000, 0x1000}, 0}, /* 18 */
    {"lb", {"p aw 1 n d", "p aw 1 n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 19 */
    {"live", {"l ay 1 v", "l ih 1 v", NULL}, {0x3001, 0x2000, 0x0}, 3}, /* 20 */
    {"lives", {"l ay 1 v z", "l ih 1 v z", NULL}, {0x1000, 0x2000, 0x0}, 3}, /* 21 */
    {"m", {"m iy 1 - t ax r", "m iy 1 - t ax r z", "eh 1 m"}, {0x1000, 0x1000, 0x1000}, 0}, /* 22 */
    {"mb", {"m eh 1 - g ax - b ay 2 t", "m eh 1 - g ax - b ay 2 t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 23 */
    {"mg", {"m ih 1 - l ax - g r ae 2 m", "m ih 1 - l ax - g r ae 2 m z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 24 */
    {"mi", {"m ay 1 l", "m ay 1 l z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 25 */
    {"min", {"m ih 1 - n ih t", "m ih 1 - n ih t s", "m ih 1 - n ax - m ax m"}, {0x1000, 0x1000, 0x1000}, 0}, /* 26 */
    {"misread", {"m ih s - r iy 1 d", "m ih s - r eh 1 d", NULL}, {0x2000, 0x2000, 0x0}, 2}, /* 27 */
    {"ml", {"m ih 1 - l ax - l iy - t ax r", "m ih 1 - l ax - l iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 28 */
    {"mm", {"m ih 1 - l ax - m iy 2 - t ax r", "m ih 1 - l ax - m iy 2 - t ax r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 29 */
    {"mpg", {"m ay 1 l - p er r - g ae 1 - l ax n", "m ay 1 l z - p er r - g ae 1 - l ax n", "eh 1 m - p iy 1 - jh iy 1"}, {0x1000, 0x1000, 0x1000}, 0}, /* 30 */
    {"mph", {"m ay 1 l - p er - r aw 1 - ax r", "m ay 1 l z - p er - r aw 1 - ax r", "eh 1 m - p iy 1 - ey 1 ch"}, {0x1000, 0x1000, 0x1000}, 0}, /* 31 */
    {"msec", {"m ih 1 - l ih - s eh - k ax n d", "m ih 1 - l ax - s eh 2 - k ax n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 32 */
    {"oz", {"aw 1 n s", "aw 1 n - s ih z", "aa 1 z"}, {0x1000, 0x1000, 0x1000}, 0}, /* 33 */
    {"proofread", {"p r uw 1 - f r iy d", "p r uw 1 - f r eh 2 d", NULL}, {0x2000, 0x2000, 0x0}, 2}, /* 34 */
    {"qt", {"k w ao 1 r t", "k w ao 1 r t s", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 35 */
    {"read", {"r iy 1 d", "r eh 1 d", NULL}, {0x2000, 0x2000, 0x0}, 2}, /* 36 */
    {"sec", {"s eh 1 - k ax n d", "s eh 1 - k ax n d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 37 */
    {"tbsp", {"t ey 1 - b ax l - s p uw 2 n", "t ey 1 - b ax l - s p uw 2 n z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 38 */
    {"the", {"dh ih 1", "dh ax 1", NULL}, {0x4006, 0x4006, 0x0}, 1}, /* 39 */
    {"tsp", {"t iy 1 - s p uw 2 n", "t iy 1 - s p uw 2 n z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 40 */
    {"yd", {"y aa 1 r d", "y aa 1 r d z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 41 */
    {"yr", {"y iy 1 r", "y ih 1 r z", NULL}, {0x1000, 0x1000, 0x0}, 0}, /* 42 */
};

/* tagger rules @0x0D5D2BE8 (63 x 0x1c): from, to, template, ctx1, ctx2, word */
static const tag_rule RULES[63] = {
    {0x3001, 0x1000, 7, 0x0, 0x0, NULL},
    {0x2000, 0x1000, 0, 0x3001, 0x0, NULL},
    {0x2000, 0x1000, 7, 0x0, 0x0, NULL},
    {0x1000, 0x2000, 0, 0x4001, 0x0, NULL},
    {0x4003, 0x3002, 3, 0x4003, 0x0, NULL},
    {0x3001, 0x3002, 1, 0x2000, 0x0, NULL},
    {0x3001, 0x3002, 4, 0x1000, 0x0, NULL},
    {0x2000, 0x1000, 2, 0x4009, 0x0, NULL},
    {0x1000, 0x2000, 0, 0x1002, 0x0, NULL},
    {0x1000, 0x2000, 0, 0x1001, 0x0, NULL},
    {0x1000, 0x2000, 0, 0x3002, 0x0, NULL},
    {0x2000, 0x1000, 1, 0x4001, 0x0, NULL},
    {0x3001, 0x3002, 4, 0x2000, 0x3001, NULL},
    {0x2000, 0x1000, 4, 0x1000, 0x2000, NULL},
    {0x1000, 0x3001, 1, 0x3001, 0x0, NULL},
    {0x2000, 0x1000, 1, 0x4004, 0x0, NULL},
    {0x3001, 0x2000, 0, 0x4001, 0x0, NULL},
    {0x1000, 0x2000, 4, 0x4009, 0x3002, NULL},
    {0x1000, 0x2000, 4, 0x4009, 0x3001, NULL},
    {0x3002, 0x4009, 4, 0x1000, 0x4009, NULL},
    {0x3002, 0x4009, 5, 0x2000, 0x1000, NULL},
    {0x3001, 0x3002, 1, 0x3002, 0x0, NULL},
    {0x1000, 0x2000, 1, 0x1003, 0x0, NULL},
    {0x3002, 0x3001, 4, 0x4009, 0x1000, NULL},
    {0x1000, 0x2000, 4, 0x4005, 0x4009, NULL},
    {0x3001, 0x3002, 4, 0x3002, 0x3001, NULL},
    {0x4009, 0x2000, 0, 0x4001, 0x0, NULL},
    {0x3002, 0x4003, 1, 0x1002, 0x0, NULL},
    {0x3001, 0x1000, 4, 0x3001, 0x4009, NULL},
    {0x1000, 0x2000, 5, 0x4005, 0x1000, NULL},
    {0x1000, 0x2000, 0, 0x4001, 0x0, NULL},
    {0x2000, 0x1000, 4, 0x0, 0x2000, NULL},
    {0x3001, 0x2000, 4, 0x2000, 0x3001, NULL},
    {0x4003, 0x3002, 4, 0x0, 0x0, NULL},
    {0x3002, 0x4009, 5, 0x4009, 0x0, NULL},
    {0x3001, 0x3002, 6, 0x2000, 0x3001, NULL},
    {0x3002, 0x4009, 1, 0x1000, 0x0, NULL},
    {0x2000, 0x1000, 4, 0x4003, 0x2000, NULL},
    {0x3001, 0x1000, 4, 0x4009, 0x4009, NULL},
    {0x1000, 0x2000, 4, 0x4009, 0x1001, NULL},
    {0x3001, 0x1000, 4, 0x1000, 0x2000, NULL},
    {0x3001, 0x3002, 0, 0x4001, 0x0, NULL},
    {0x3001, 0x1000, 1, 0x4001, 0x0, NULL},
    {0x3001, 0x3002, 1, 0x4001, 0x0, NULL},
    {0x3001, 0x1000, 4, 0x0, 0x4009, NULL},
    {0x2000, 0x1000, 6, 0x0, 0x2000, NULL},
    {0x1000, 0x2000, 0, 0x1002, 0x0, NULL},
    {0x3001, 0x2000, 4, 0x4009, 0x3002, NULL},
    {0x3002, 0x3001, 4, 0x4003, 0x1000, NULL},
    {0x4003, 0x3002, 4, 0x4009, 0x3001, NULL},
    {0x3002, 0x4009, 1, 0x2000, 0x0, NULL},
    {0x1000, 0x3001, 1, 0x3001, 0x0, NULL},
    {0x3002, 0x4003, 1, 0x1001, 0x0, NULL},
    {0x4003, 0x3002, 0, 0x4001, 0x0, NULL},
    {0x1000, 0x2000, 0, 0x3002, 0x0, NULL},
    {0x2000, 0x1000, 6, 0x4004, 0x0, NULL},
    {0x1000, 0x2000, 0, 0x4001, 0x0, NULL},
    {0x1000, 0x2000, 0, 0x1001, 0x0, NULL},
    {0x3002, 0x3001, 6, 0x4009, 0x1000, NULL},
    {0x1000, 0x3001, 4, 0x3002, 0x1000, NULL},
    {0x4003, 0x3002, 4, 0x3002, 0x3001, NULL},
    {0x4006, 0x1000, 8, 0x4006, 0x0, "a"},
    {0x2000, 0x3001, 4, 0x4006, 0x1000, NULL},
};

/* letter names for spelled words @0x0D60C358 */
static const char *const LETTER_NAMES[26] = {
    "ey 1", "b iy 1", "s iy 1", "d iy 1", "iy 1", "eh 1 f", "jh iy 1", "ey 1 ch", "ay 1", "jh ey 1", "k ey 1", "eh l 1", "eh m 1", "eh n 1", "ow 1", "p iy 1", "k y uw 1", "aa r 1", "eh 1 s", "t iy 1", "y uw 1", "v iy 1", "d ah 1 - b ax - l y uw 2", "eh 1 k s", "w ay 1", "z iy 1"
};

/* internal phone code -> SAPI phone id @0x0D5D1DB0 (43 = stress 1, 44 = stress 2, 46 = syllable) */
static const short PHONE_MAP[47] = {
    28, 27, 21, 11, 10, 12, 13, 43, 15, 22, 23, 16, 36, 14, 35, 44, 0, 7, 46, 47, 38, 31, 26, 32, 33, 34, 24, 45, 42, 20, 39, 48, 40, 49, 37, 17, 41, 19, 30, 25, 18, 29, 0, 8, 9, 0, 1
};

/* SAPI rate adjustment factors 3^(r/10) @0x0D5D1C28 */
static const float RATE_TAB[19] = {
    1.0f, 1.1161232f, 1.245731f, 1.3903892f, 1.55184555f, 1.73205078f, 1.933182f, 2.15766931f, 2.40822458f, 2.68787527f, 3.0f, 3.3483696f, 3.73719287f, 4.17116737f, 4.65553665f, 5.19615221f, 5.79954624f, 6.47300768f, 7.22467422f
};

/* vowels (first phone of the next word for "the"/"of an") @0x0D5D1EE4 */
static const uint16_t VOWELS[16] = {10, 11, 12, 13, 14, 15, 16, 21, 22, 23, 27, 28, 35, 36, 43, 44};

/* reversed suffixes @0x0D5D6520 (33 x 0x18): text, record */
static const morph_suffix SUFFIXES[33] = {
    {"RE", 5},
    {"TSE", 6},
    {"GNI", 2},
    {"ELBA", 14},
    {"ELBI", 14},
    {"YLDE", 12},
    {"YLBA", 24},
    {"YLBI", 24},
    {"YLLACI", 26},
    {"YLI", 28},
    {"YL", 13},
    {"Y", 11},
    {"TNEM", 8},
    {"RO", 7},
    {"SSEN", 15},
    {"SSEL", 10},
    {"EZICI", 30},
    {"EZI", 17},
    {"ZI", 18},
    {"MSICI", 29},
    {"MSI", 16},
    {"DE", 1},
    {"S'", 3},
    {"S", 0},
    {"'", 4},
    {"EGA", 9},
    {"DOOH", 19},
    {"LUF", 20},
    {"EKIL", 21},
    {"ESIW", 22},
    {"HSI", 23},
    {"PIHS", 25},
    {"EMOS", 27},
};

/* suffix records @0x0D606178 (0x328 bytes): phones (converted to ids at load time), POS maps, flags @+0x324 */
static const morph_record RECORDS[31] = {
    {"s", {{0x2000, 0x2000}, {0x1000, 0x1000}}, 2, 0x0},
    {"d", {{0x2000, 0x2000}, {0x2000, 0x3001}}, 2, 0x7},
    {"IH NG", {{0x2000, 0x2000}, {0x2000, 0x3001}, {0x2000, 0x1000}}, 3, 0x5},
    {"s", {{0x1000, 0x1000}}, 1, 0x0},
    {"s", {{0x1000, 0x1000}}, 1, 0x0},
    {"ER", {{0x2000, 0x1000}, {0x3001, 0x3001}, {0x3002, 0x3002}, {0x3001, 0x3002}}, 4, 0x7},
    {"AX s t", {{0x3001, 0x3001}, {0x3002, 0x3002}, {0x3001, 0x3002}}, 3, 0x7},
    {"ER", {{0x2000, 0x1000}}, 1, 0x5},
    {"m AX n t", {{0x2000, 0x1000}}, 1, 0x2},
    {"IH JH", {{0x2000, 0x1000}}, 1, 0x5},
    {"l IH s", {{0x1000, 0x3001}}, 1, 0x2},
    {"IY", {{0x1000, 0x3001}, {0x3001, 0x3002}}, 2, 0x5},
    {"AX d l IY", {{0x2000, 0x3001}, {0x2000, 0x3002}}, 2, 0x7},
    {"l IY", {{0x1000, 0x3001}, {0x3001, 0x3002}}, 2, 0x10},
    {"AX - b AX l", {{0x2000, 0x3001}, {0x1000, 0x3001}}, 2, 0x7},
    {"n IH s", {{0x3001, 0x1000}}, 1, 0x2},
    {"IH z AX m", {{0x3001, 0x1000}, {0x1000, 0x1000}}, 2, 0x1},
    {"AY z", {{0x1000, 0x2000}, {0x3001, 0x2000}}, 2, 0x1},
    {"AY z", {{0x1000, 0x2000}, {0x3001, 0x2000}}, 2, 0x1},
    {"h UH d", {{0x1000, 0x1000}}, 1, 0x0},
    {"f AX l", {{0x1000, 0x3001}, {0x2000, 0x3001}}, 2, 0x0},
    {"l AY k", {{0x1000, 0x3001}}, 1, 0x0},
    {"w AY z", {{0x1000, 0x3001}}, 1, 0x2},
    {"IH SH", {{0x1000, 0x3001}}, 1, 0x5},
    {"AX - b l IY", {{0x2000, 0x3002}, {0x1000, 0x3002}}, 2, 0x7},
    {"SH IH 2 p", {{0x1000, 0x1000}}, 1, 0x0},
    {"L IY", {{0x3001, 0x3002}}, 1, 0x0},
    {"S AX M", {{0x1000, 0x3001}}, 1, 0x2},
    {"AX L IY", {{0x1000, 0x3002}}, 1, 0xc},
    {"IH z AX m", {{0x3001, 0x1000}, {0x1000, 0x1000}}, 2, 0x1},
    {"AY z", {{0x1000, 0x2000}, {0x3001, 0x2000}}, 2, 0x1},
};

/* phone class flags per SAPI phone id @0x0D5D6838 (bit0 consonant, bit1 voiced, bit2 sibilant) */
static const uint8_t PHONE_CLASS[50] = {1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 5, 3, 3, 2, 2, 2, 1, 3, 1, 2, 2, 7, 1, 3, 3, 3, 3, 2, 2, 1, 3, 1, 5, 1, 1, 2, 2, 3, 3, 3, 3, 7};
