#!/usr/bin/env python3
"""Generates Shared/Bridge/cv_fold_table.h: Latin letters outside ASCII -> plain ASCII spelling.

The engine's letter-to-sound model only knows a-z (plus ' and .), so an accented letter is simply
skipped ("resume" with accents would lose its vowels). Folding them keeps the word pronounceable.
Run: python3 tools/gen_fold_table.py > Shared/Bridge/cv_fold_table.h
"""
import re, unicodedata

SPECIAL = {
    'SHARP S': 'ss', 'AE': 'ae', 'OE': 'oe', 'IJ': 'ij', 'ETH': 'd', 'THORN': 'th', 'ENG': 'ng',
    'DOTLESS I': 'i', 'LONG S': 's', 'KRA': 'k', 'DOTLESS J': 'j', 'SCHWA': 'e', 'OI': 'oi',
    'OU': 'ou', 'HV': 'hv', 'DZ': 'dz', 'LJ': 'lj', 'NJ': 'nj', 'DEZH': 'dz', 'EZH': 'z',
}
RANGES = [(0x00C0, 0x024F), (0x1E00, 0x1EFF)]

def fold(cp):
    ch = chr(cp)
    name = unicodedata.name(ch, '')
    if not name.startswith('LATIN '):
        return None
    base = ''.join(c for c in unicodedata.normalize('NFKD', ch) if 'a' <= c.lower() <= 'z')
    if base:
        return base
    m = re.match(r'LATIN (SMALL|CAPITAL) (?:LETTER|LIGATURE) (.+?)(?: WITH .*)?$', name)
    if not m:
        return None
    small, what = m.group(1) == 'SMALL', m.group(2)
    what = re.sub(r'^(TURNED|REVERSED|SMALL CAPITAL|INSULAR|MIDDLE-WELSH|BROKEN|SIDEWAYS|OPEN|CLOSED) ', '', what)
    if what in SPECIAL:
        s = SPECIAL[what]
    elif re.fullmatch(r'[A-Z]', what):
        s = what.lower()
    else:
        return None
    return s if small else s[0].upper() + s[1:]

rows = []
for lo, hi in RANGES:
    for cp in range(lo, hi + 1):
        if cp in (0xD7, 0xF7):  # multiplication / division signs are not letters
            continue
        f = fold(cp)
        if f:
            rows.append((cp, f))

print('/* Generated by tools/gen_fold_table.py - Latin letter -> ASCII spelling, sorted by code point. */')
print('typedef struct { unsigned short cp; const char *ascii; } cv_fold;')
print('static const cv_fold CV_FOLD[] = {')
for cp, f in rows:
    print('    {0x%04X, "%s"}, /* %s */' % (cp, f, unicodedata.name(chr(cp))))
print('};')
